### ISSUE TITLE
Addresses fixed by board

### ISSUE THREAD

**Issue by soundstorm** [545ch4/flippie#1]
The addresses are fixed by the ADDR8/EN pin on PCB, if daisy chaining them, ADDR1-ADDR8 must correspond the panels DIP switch position (which should be different than always 00000001). So the addr shift register needs to be filled and toggled once.
[I already built a shift-register only pcb](https://github.com/ArduinoHannover/FlipperCTRL), but missed the current limit on VS and got the address problem too, as my last register is synced with the others. Will fix that in next revision.

**Comment by 545ch4** [comment]
I don't quite understand your issue here. Let's just explain my thoughts on this "address-problem" at flippie:

The address lines (as well as the FP2800A inputs) are 24V pulled-up logic lines. So to drive them in a very simple way, would need just a NMOS to short the appropriate line to GND. By doing so, you have an inverting driver. That's why the modules connected via flippie, must have their address DIP-switches on the module inverted as well.

I've designed the ADDR8/EN line directly as an discrete output of the MCU to emulate a real kill-switch-like EN line. All other lines ADDR1-ADDR7 are driven by the shift-register.

So, there's no "address-problem" at flippie. It is working with multiple modules (tested) as well as with only a single one.

**Comment by soundstorm** [comment]
Nah, missed that in the Readme... Nevermind. 128 Displays should be enough...
